### ISSUE TITLE
TCP backlog

### ISSUE THREAD

**Issue by firemanxbr** [reallyenglish/k8s-redis-ha#2]
2017-06-14T04:57:00.630562455Z 1:M 14 Jun 04:57:00.630 # WARNING: The TCP
backlog setting of 511 cannot be enforced because
/proc/sys/net/core/somaxconn is set to the lower value of 128.

I'm try fixing on image, but the read-only will be a problem in this case. I'll investigating more.

**Comment by ochko** [comment]
It's just warning, but If you need more connection backlogs:

Docker has `--sysctl` option which might be useful. And you could try `sysctl -w net.core.somaxconn=65535` command in the `entrypoint`.
